// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by @sveltejs/adapter-cloudflare",
  include: [
    "/*"
  ],
  exclude: [
    "/_app/*",
    "/.DS_Store",
    "/cartoon-head-with-outline.svg",
    "/cartoon-head.png",
    "/cartoon-head.svg",
    "/favicon.svg",
    "/nyan-unicorn.webp"
  ]
};

// ../../../Library/pnpm/global/5/.pnpm/wrangler@4.53.0/node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "/Users/mmcdermott/mark-mcdermott/themeforseen-proj/themeforseen.com/.wrangler/tmp/pages-fJprbk/bundledWorker-0.4955436111046492.mjs";
import { isRoutingRuleMatch } from "/Users/mmcdermott/Library/pnpm/global/5/.pnpm/wrangler@4.53.0/node_modules/wrangler/templates/pages-dev-util.ts";
export * from "/Users/mmcdermott/mark-mcdermott/themeforseen-proj/themeforseen.com/.wrangler/tmp/pages-fJprbk/bundledWorker-0.4955436111046492.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        const workerAsHandler = worker;
        if (workerAsHandler.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return workerAsHandler.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=48muz2d8ycr.js.map
